name: Hub
main: Terpz710\Hub
version: 1.0.0
api: 5.0.0
author: Terpz710
description: Adds /hub and /sethub
permissions:
  sethub.command:
    description: Allows players to use the /sethub command
    default: op
  hub.command:
    description: Allows players to use the /hub command
    default: true